# Generated by Django 5.2 on 2025-04-08 18:06

from django.db import migrations, models

import shortener.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField()),
                (
                    "token",
                    models.CharField(
                        default=shortener.models.generate_token,
                        max_length=6,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("click_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
